In [1]:
import numpy as np
import pandas as pd

In [2]:
##https://www.kaggle.com/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews?select=IMDB+Dataset.csv
df= pd.read_csv('IMDB Dataset.csv')
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

# sentiment col in replace positive for 1 & negative for 0

In [3]:
df['sentiment'].replace({'positive':1,'negative':0},inplace=True)

In [4]:
df.head()

review  sentiment
0  One of the other reviewers has mentioned that ...          1
1  A wonderful little production. <br /><br />The...          1
2  I thought this was a wonderful way to spend ti...          1
3  Basically there's a family where a little boy ...          0
4  Petter Mattei's "Love in the Time of Money" is...          1

# Text Cleaning:-

1)Remove All Html Tags

In [5]:
import re

In [6]:
def clean_html_tags(text):
    clean = re.compile('<.*?>')
    return re.sub(clean, '',text)

In [7]:
df['review'] = df['review'].apply(clean_html_tags)

2)Converting Everything to lower

In [8]:
def convert_lower(text):
    return text.lower()

In [9]:
df['review'] = df['review'].apply(convert_lower)

3)Remove Special Character

In [10]:
def remove_special(text):
    x=''
    for i in text:
        if i.isalnum():
            x=x+i
        else:
            x=x+ ' '
    return x

In [11]:
##Check For:-
remove_special("i am % chetan")

'i am   chetan'

In [12]:
df['review'] = df['review'].apply(remove_special)

4)Remove the stop words 

In [13]:
import nltk

In [14]:
from nltk.corpus import stopwords

In [15]:
##show all stopwords:-
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [16]:
len(stopwords.words('english'))

179

In [17]:
def remove_stopwords(text):
    x=[]
    for i in text.split():
        if i not in stopwords.words('english'):
            x.append(i)
    y=x[:]
    x.clear()
    return y

In [18]:
df['review'] = df['review'].apply(remove_stopwords)

In [19]:
df

review  sentiment
0      [one, reviewers, mentioned, watching, 1, oz, e...          1
1      [wonderful, little, production, filming, techn...          1
2      [thought, wonderful, way, spend, time, hot, su...          1
3      [basically, family, little, boy, jake, thinks,...          0
4      [petter, mattei, love, time, money, visually, ...          1
...                                                  ...        ...
49995  [thought, movie, right, good, job, creative, o...          1
49996  [bad, plot, bad, dialogue, bad, acting, idioti...          0
49997  [catholic, taught, parochial, elementary, scho...          0
49998  [going, disagree, previous, comment, side, mal...          0
49999  [one, expects, star, trek, movies, high, art, ...          0

[50000 rows x 2 columns]

5)Perform Stemming(play,playing,played to change play)

In [20]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [21]:
y = []
def stem_words(text):
    for i in text:
        y.append(ps.stem(i))
    z=y[:]
    y.clear()
    return z

In [22]:
df['review'] = df['review'].apply(stem_words)

In [23]:
##join back
def join_back(list_input):
    return " ".join(list_input)

In [24]:
df['review'] = df['review'].apply(join_back)

In [25]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=100)

In [26]:
df.head()

review  sentiment
0  one review mention watch 1 oz episod hook righ...          1
1  wonder littl product film techniqu unassum old...          1
2  thought wonder way spend time hot summer weeke...          1
3  basic famili littl boy jake think zombi closet...          0
4  petter mattei love time money visual stun film...          1

In [27]:
QQ = cv.fit_transform(["one review mention watch"]).toarray()
QQ

array([[1, 1, 1, 1]], dtype=int64)

In [28]:
X = cv.fit_transform(df['review']).toarray()

In [29]:
X.shape

(50000, 100)

In [30]:
X[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 2, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 2, 1, 0, 0, 0, 1, 4, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 3, 0, 1, 0, 0, 1, 0], dtype=int64)

In [31]:
y = df.iloc[:,-1].values

In [32]:
y.shape

(50000,)

In [33]:
y

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [34]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=100)

In [35]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
clf1 = GaussianNB()
clf2 = MultinomialNB()
clf3 = BernoulliNB()

In [36]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)
clf3.fit(X_train,y_train)

BernoulliNB()

In [37]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)
y_pred3 = clf3.predict(X_test)

In [38]:
from sklearn.metrics import accuracy_score
print("GaussianNB:- ",accuracy_score(y_test,y_pred1))
print("MultinomialNB:- ",accuracy_score(y_test,y_pred2))
print("BernoulliNB:- ",accuracy_score(y_test,y_pred3))

GaussianNB:-  0.7221
MultinomialNB:-  0.7369
BernoulliNB:-  0.7291
